#let default = (
  variant: "iec",
  scale: (x: 1.0, y: 1.0),
  stroke: (
    thickness: .8pt,
    paint: auto,
    join: "miter",
    cap: "butt",
    miter-limit: 4,
    dash: none,
  ),
  fill: auto,
  background: white,
  foreground: black,
  label: (
    scale: auto,
    content: none,
    distance: 7pt,
    anchor: "north",
  ),
  node: (
    stroke: (
      thickness: .4pt,
      paint: auto,
    ),
    fill: auto,
    nofill: auto,
    radius: .05,
  ),
  wire: (
    stroke: (
      thickness: .5pt,
    ),
    marker: (
      min-dist: 0.25,
      max-dist: 0.35,
      text-gap: 0.18,
      side-gap: 0.35,
      kink-threshold: 0.25,
    ),
    spacing: 0.15,
  ),
  arrow: (
    symbol: ">",
    scale: 1.0,
    angle: 55deg,
    length: 40pt,
    ratio: (0.5, 0.5),
    stroke: (
      thickness: 1pt,
      paint: auto,
    ),
    variable: (
      symbol: auto,
      scale: 1.0,
      stroke: auto,
      length: auto,
      angle: auto,
      ratio: auto,
    ),
    preset: (
      symbol: "|",
      scale: 1.0,
      stroke: auto,
      length: auto,
      angle: auto,
      ratio: auto,
      width: 10pt,
    ),
    sensor: (
      symbol: none,
      scale: 1.0,
      stroke: auto,
      length: auto,
      sensor-length: 12pt,
      angle: auto,
      ratio: auto,
    ),
    radiation: (
      symbol: auto,
      scale: 1,
      stroke: (
        thickness: 0.55pt,
      ),
      distance: 3pt,
      length: 12pt,
      angle: -120deg,
      reversed: false,
    ),
    adjustable: (
      symbol: auto,
      scale: 1.0,
      stroke: auto,
      length: 0.8,
    ),
  ),
  decoration: (
    symbol: ">",
    scale: 1.0,
    stroke: (
      thickness: .6pt,
      paint: auto,
    ),
    content: none,
    distance: 9pt,
    position: (x: "east", y: "north"),
    anchor: "north-east",
    invert: false,
    current: (
      symbol: auto,
      scale: 1.0,
      stroke: auto,
      content: auto,
      distance: auto,
      position: auto,
      anchor: auto,
      invert: auto,
      wire: (
        symbol: auto,
        scale: auto,
        stroke: auto,
        content: auto,
        distance: 7pt,
        position: 50%,
        anchor: "north",
        invert: auto,
      ),
    ),
    flow: (
      symbol: auto,
      scale: 1.0,
      stroke: (
        thickness: 0.55pt,
        cap: auto,
        miter-limit: auto,
        dash: auto,
      ),
      content: auto,
      distance: auto,
      position: auto,
      anchor: auto,
      invert: auto,
      length: 0.7,
      indent: 0.2,
      label-ratio: 50%,
    ),
    voltage: (
      symbol: auto,
      scale: 1.0,
      stroke: auto,
      content: auto,
      distance: 2pt,
      position: auto,
      anchor: auto,
      invert: auto,
      start: (-.4, .1),
      end: (.4, .1),
      center: (0, .3),
    ),
  ),
  debug: (
    stroke: (
      thickness: .2pt,
      paint: red,
    ),
    enabled: false,
    radius: .7pt,
    angle: -30deg,
    shift: 3pt,
    inset: 1pt,
    font: 3pt,
    fill: red,
  ),
  // Components
  stub: (
    scale: auto,
    length: .8,
  ),
  cabinet: (
    variant: auto,
    scale: auto,
    stroke: auto,
    fill: auto,
    width: 15,
    height: 25,
    padding: 0.2,
    spacing: 0.5,
    textsize: 1em,
  ),
  mcb: (
    width: 1,
    height: 2.2,
    fill: rgb("#f0f0f0"),
    text-size: 4pt,
    text-size-bottom: 3pt,
  ),
  dinrail: (
    length: 13.4,
    height: 0.8,
    fill: silver,
  ),
  terminal: (
    fill: gray.lighten(50%),
    stroke: 0.5pt,
    text-size: 6pt,
  ),
  generic_box: (
    width: 3.0,        
  height: 3.0,             
  fill: white.darken(2%),  
  stroke: black + 0.8pt,   
  text-size: 8pt,          
  pin-text-size: 5pt,
  )
)

